#!/bin/sh

ROGUESTAR_ENGINE="roguestar-engine version over begin"
ROGUESTAR_UI="roguestar-gl-bin $@"

faucet 5618 --out --in --unix --once ${ROGUESTAR_ENGINE} &

sleep 2

hose localhost 5618 --out --in --unix ${ROGUESTAR_UI} &
